### ISSUE TITLE
"я твой дом труба шатал" - определяется неверно

### ISSUE THREAD

**Issue by KOLANICH** [morfeusys/speechmarkup#1]
http://markup.dusi.mobi/api/text?lang=ru&text=%D1%8F%20%D1%82%D0%B2%D0%BE%D0%B9%20%D0%B4%D0%BE%D0%BC%20%D1%82%D1%80%D1%83%D0%B1%D0%B0%20%D1%88%D0%B0%D1%82%D0%B0%D0%BB

**Comment by morfeusys** [comment]
Ну город Дом есть и чего? Удалим ))

вторник, 11 ноября 2014 г. пользователь KOLANICH написал:
