### ISSUE TITLE
Не правильно обрабатываются города

### ISSUE THREAD

**Issue by alexpan0** [morfeusys/speechmarkup#7]
Делаем запрос: "деревня Софьино"

Получаем ответ:
{
  "string": "деревня Софьино",
  "tokens": []
}

На http://www.geonames.org:
Sof’ino ca. 202 m
Sof'ino,Sofino,Софьино
819455
P PPL populated place
Russia RU » Moscow Oblast 47
55.51619, 37.01068

**Comment by morfeusys** [comment]
В базе города только численностью больше 15000 человек, без деревень и сел

**Comment by alexpan0** [comment]
Очень жаль... Нам как раз нужны населенные пункты Московской области, а не столицы стран мира...
Может вам как то Яндекс попользовать? У них с населенными пунктами РФ все не плохо.
Вот пример сотрудничества с Яндексом - dadata.ru
